import { useState, useRef, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Send, AlertTriangle, FileText, Share2, ArrowLeft } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { themes } from '../theme/themes';
import { ScreenHeader, SensitiveBlur } from '../components/ScreenHeader';
import { ShareSheet } from '../components/BottomSheets';

export function AskHealthyScreen() {
  const {
    theme,
    chatMessages,
    addChatMessage,
    showSafetyEscalation,
  } = useApp();
  const tokens = themes[theme];
  const [input, setInput] = useState('');
  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages, showSafetyEscalation]);

  const send = () => {
    if (!input.trim()) return;
    addChatMessage(input.trim());
    setInput('');
  };

  if (showSafetyEscalation) {
    return <SafetyEscalation />;
  }

  return (
    <div className="screen chat-screen">
      <ScreenHeader title="Ask Healthy" subtitle="Your action companion" />

      <div className="chat-hint" style={{ color: tokens.textMuted }}>
        Try: "My face is breaking out badly" or "severe pain"
      </div>

      <div className="chat-messages">
        {chatMessages.map((msg) => (
          <motion.div
            key={msg.id}
            className={`chat-bubble ${msg.role}`}
            initial={{ opacity: 0, y: 12, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ type: 'spring', damping: 20 }}
            style={
              msg.role === 'user'
                ? {
                    background: tokens.primary,
                    color: '#fff',
                    alignSelf: 'flex-end',
                  }
                : {
                    background: tokens.surface,
                    color: tokens.text,
                    border: `1px solid ${tokens.border}`,
                    alignSelf: 'flex-start',
                  }
            }
          >
            <SensitiveBlur sensitive={msg.role === 'user'}>
              {msg.text}
            </SensitiveBlur>
          </motion.div>
        ))}
        <div ref={chatEndRef} />
      </div>

      <div
        className="chat-input-bar"
        style={{
          background: tokens.surface,
          borderTop: `1px solid ${tokens.border}`,
        }}
      >
        <input
          type="text"
          className="chat-input"
          placeholder="Describe what's going on..."
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && send()}
          style={{
            background: tokens.surfaceElevated,
            border: `1.5px solid ${tokens.border}`,
            color: tokens.text,
          }}
        />
        <motion.button
          className="send-btn"
          whileTap={{ scale: 0.9 }}
          onClick={send}
          style={{ background: tokens.primary }}
        >
          <Send size={20} color="#fff" />
        </motion.button>
      </div>
    </div>
  );
}

function SafetyEscalation() {
  const { theme, resetChat, openShareSheet, chatMessages } = useApp();
  const tokens = themes[theme];

  const userConcern = chatMessages.filter((m) => m.role === 'user').pop()?.text ?? 'Reported concern';

  const summary = {
    timeline: [
      { date: 'Today', event: 'Onset of symptoms reported via Ask Healthy' },
      { date: 'Past 3 days', event: 'Mild discomfort noted, no remedies tried yet' },
      { date: 'Ongoing', event: 'Using Healthy.Ai action tracking for wellness goals' },
    ],
    remedies: ['None reported at this time'],
    blockers: ['Not applicable — escalated for safety'],
    disclaimer:
      'This summary was generated by Healthy.Ai for visit preparation only. It is not a medical diagnosis. Please seek professional evaluation for symptoms requiring urgent care.',
  };

  return (
    <motion.div
      className="screen safety-screen"
      initial={{ opacity: 0, x: 40 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ type: 'spring', damping: 25 }}
    >
      <div className="safety-header">
        <button className="back-btn" onClick={resetChat} style={{ color: tokens.text }}>
          <ArrowLeft size={22} />
        </button>
        <ScreenHeader title="Safety Check" showThemeToggle={false} />
      </div>

      <div
        className="warning-banner"
        style={{
          background: `linear-gradient(135deg, ${tokens.danger}22, ${tokens.danger}11)`,
          border: `2px solid ${tokens.danger}`,
        }}
      >
        <AlertTriangle size={28} style={{ color: tokens.danger, flexShrink: 0 }} />
        <div>
          <h3 style={{ color: tokens.danger, margin: 0 }}>Professional Care Recommended</h3>
          <p style={{ color: tokens.text, margin: '6px 0 0', fontSize: 14, lineHeight: 1.5 }}>
            Based on what you've shared, formal medical evaluation or clinic triage may be needed. Please don't delay seeking care.
          </p>
        </div>
      </div>

      <div
        className="doctor-summary-card"
        style={{
          background: tokens.cardGradient,
          border: `1px solid ${tokens.border}`,
          boxShadow: tokens.shadow,
        }}
      >
        <div className="summary-header">
          <FileText size={22} style={{ color: tokens.primary }} />
          <h3 style={{ color: tokens.text, margin: 0 }}>Doctor-Ready Summary</h3>
        </div>

        <div className="summary-section">
          <h4 style={{ color: tokens.textSecondary }}>Primary Concern</h4>
          <p style={{ color: tokens.text }}>
            <SensitiveBlur sensitive>{userConcern}</SensitiveBlur>
          </p>
        </div>

        <div className="summary-section">
          <h4 style={{ color: tokens.textSecondary }}>Timeline</h4>
          {summary.timeline.map((t, i) => (
            <div key={i} className="timeline-row">
              <span className="timeline-date" style={{ color: tokens.primary }}>{t.date}</span>
              <span style={{ color: tokens.textMuted }}>{t.event}</span>
            </div>
          ))}
        </div>

        <div className="summary-section">
          <h4 style={{ color: tokens.textSecondary }}>Remedies Tried</h4>
          <ul style={{ color: tokens.textMuted, margin: 0, paddingLeft: 18 }}>
            {summary.remedies.map((r, i) => (
              <li key={i}>{r}</li>
            ))}
          </ul>
        </div>

        <div className="summary-section">
          <h4 style={{ color: tokens.textSecondary }}>Logged Blockers</h4>
          <p style={{ color: tokens.textMuted }}>{summary.blockers[0]}</p>
        </div>

        <div
          className="disclaimer-box"
          style={{
            background: tokens.surfaceElevated,
            border: `1px solid ${tokens.border}`,
            color: tokens.textMuted,
          }}
        >
          {summary.disclaimer}
        </div>
      </div>

      <motion.button
        className="export-btn"
        whileTap={{ scale: 0.97 }}
        onClick={openShareSheet}
        style={{
          background: tokens.heroGradient,
          color: '#fff',
          boxShadow: tokens.shadow,
        }}
      >
        <Share2 size={20} />
        Export Summary
      </motion.button>

      <ShareSheet />
    </motion.div>
  );
}

export { SafetyEscalation };
